# Autocomplete
autoload -Uz compinit && compinit

# For uv tool install
export PATH="$HOME/.local/bin:$PATH"

# Starship
eval "$(starship init zsh)"

# Machine specific stuff
if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi